---
- name: Install applications in Docker containers
  hosts: webservers
  vars:
    miniflux_path: /var/www/miniflux
    wallabag_path: /var/www/wallabag
    wekan_path: /var/www/wekan
  roles:
    - miniflux
    - wallabag
    - wekan
