---
- name: Install applications in Docker containers
  hosts: webservers
  vars:
    miniflux_path: /var/www/miniflux
    wallabag_path: /var/www/wallabag
    wekan_path: /var/www/wekan
    lobsters_path: /var/www/lobsters
  roles:
    - { role: lobsters, tags: lobsters }
    - { role: miniflux, tags: miniflux }
    - { role: wallabag, tags: wallabag }
    - { role: wekan, tags: wekan }
