---
- name: Ensures the freshrss folder exists
  file:
    path: "{{ freshrss_path }}"
    state: directory

- name: Create the FreshRSS container
  docker_container:
    name: freshrss
    image: freshrss/freshrss
    restart_policy: unless-stopped
    networks:
      - name: web
    volumes:
      - "{{ freshrss_path }}/data:/var/www/FreshRSS/data"
    labels:
      traefik.backend: "freshrss"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host:{{ freshrss_root_url }}"
      traefik.enable: "true"
    env:
      CRON_MIN: "*/20"
