---
- name: Ensures the Miniflux folder exists
  file:
    path: "{{ miniflux_path }}"
    state: directory

- name: Create the Miniflux network
  docker_network:
    name: miniflux

- name: Create the Postgres container
  docker_container:
    name: minifluxdb
    image: postgres:11
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: miniflux
    volumes:
      - "{{ miniflux_path }}/data:/var/lib/postgresql/data"
    env:
      POSTGRES_USER: "miniflux"
      POSTGRES_PASSWORD: "secret"

- name: Create the Miniflux containers
  docker_container:
    name: "miniflux-{{ item }}"
    image: miniflux/miniflux
    restart_policy: unless-stopped
    pull: true
    networks:
      - name: web
      - name: miniflux
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.miniflux.rule: "Host(`miniflux.{{ domain_url }}`)"
      traefik.http.routers.miniflux.entrypoints: "websecure"
      traefik.http.services.miniflux.loadbalancer.server.port: "8080"
      traefik.http.services.miniflux.loadbalancer.sticky: "true"
    env:
      DATABASE_URL: "postgres://miniflux:secret@minifluxdb/miniflux?sslmode=disable"
      RUN_MIGRATIONS: "1"
  with_sequence: count=2
