---
- name: Ensures the Wallabag folder exists
  file:
    path: "{{ wallabag_path }}"
    state: directory

- name: Create the Wallabag containers
  docker_container:
    name: "wallabag-{{ item }}"
    image: wallabag/wallabag
    restart_policy: unless-stopped
    networks:
      - name: web
    volumes:
      - "{{ wallabag_path }}/data:/var/www/wallabag/data"
      - "{{ wallabag_path }}/images:/var/www/wallabag/web/assets/images"
    labels:
      traefik.backend: "wallabag"
      traefik.docker.network: "web"
      traefik.frontend.rule: "Host:wallabag.{{ domain_url }}"
      traefik.enable: "true"
      traefik.backend.loadbalancer.stickiness: "true"
    env:
      SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.{{ domain_url }}"
  with_sequence: count=2
